In [1]:
import numpy as mynumpy
import pandas as mypanda

In [2]:
datafile2 = mypanda.read_csv("dataset_LP_2.csv" , header=None)

In [3]:
datafile1 = mypanda.read_csv("dataset_LP_1.txt", header =None)

In [4]:
def split_rearrange(datafile):
    datafile = datafile.sample(frac = 1) 
    datafile.reset_index(drop=True,inplace=True)
    info_training = datafile[:int(0.7*len(datafile))]
    info_trial = datafile[int(0.7*len(datafile)):]
    return info_training, info_trial

In [5]:
def info_wiping(datafile):
    single = mynumpy.ones((datafile.shape[0],1))
    axis_X = mynumpy.hstack((single,datafile))[:,:-1]   
    return axis_X

In [6]:
info_training2, info_trial2 = split_rearrange(datafile2)

In [7]:
practice_axis_X2 = info_wiping(info_training2)                    
practice_axis_Y2 = info_training2[info_training2.columns[-1]]      
                                                                     

In [8]:
weight2 = mynumpy.random.randn(practice_axis_X2.shape[1])
weight2.resize(practice_axis_X2.shape[1],1)
weight2

array([[-0.28798707],
       [-0.92450629],
       [ 0.170056  ],
       [-0.8902469 ]])

In [9]:
practice_axis_Y2[(mynumpy.where(practice_axis_Y2==0))[0]]= -1 

In [10]:
interim = practice_axis_Y2.to_numpy()
interim.resize(practice_axis_X2.shape[0],1)
practice_axis_Y2 = interim

In [11]:
practice_axis_Y2.shape

(700, 1)

In [12]:
practice_axis_X2.shape

(700, 4)

In [13]:
weight2.shape

(4, 1)

In [14]:

def straight_perp(axis_X,axis_y,weight):
    i=0
    while(i<1000):
        height = axis_y * mynumpy.dot(axis_X,weight)   
        iteration=0
        while(iteration<len(height)):
            if ((height[iteration])<0)[0]:
                weight = weight + (axis_y[iteration]*(axis_X[iteration].reshape((axis_X.shape[1],1)))) 
                break
            iteration=iteration+1
        i=i+1
    return weight

In [15]:
phi2 = straight_perp(practice_axis_X2,practice_axis_Y2,weight2)

In [16]:
phi2

array([[ 2.71201293],
       [-0.60330561],
       [ 3.44799125],
       [17.49704085]])

In [17]:
validity2 = 0  #testing data for datafile2
trial_axis_X2 = info_wiping(info_trial2)
trial_axis_Y2 = info_trial2[info_trial2.columns[-1]] 


In [18]:
predict_axis_Y2 = mynumpy.dot(trial_axis_X2,phi2)

In [19]:
invalid = 0
i=0
while(i<len(trial_axis_Y2)):
    if predict_axis_Y2[i]<0 and trial_axis_Y2.iloc[i]>0:
        invalid+=1
    elif predict_axis_Y2[i]>0 and trial_axis_Y2.iloc[i]<0:
        invalid+=1
    i=i+1

In [20]:
validity2 = (1- (invalid/len(trial_axis_Y2)))*100

In [21]:
validity2

99.66666666666667

In [22]:
info_training1, info_trial1 = split_rearrange(datafile1)

In [23]:
practice_axis_X1 = info_wiping(info_training1)
practice_axis_Y1 = info_training1[info_training1.columns[-1]]

In [24]:
weight1 = mynumpy.random.randn(practice_axis_X1.shape[1])
weight1.resize(5,1)
weight1

array([[-1.82428874],
       [-0.91011062],
       [ 0.55554861],
       [-1.15702897],
       [ 0.56843649]])

In [25]:
practice_axis_X1.shape

(960, 5)

In [26]:
info_trial1.shape

(412, 5)

In [27]:
datafile1.shape

(1372, 5)

In [28]:
practice_axis_Y1[(mynumpy.where(practice_axis_Y1==0))[0]]= -1

In [29]:
interim = practice_axis_Y1.to_numpy()
interim.resize(practice_axis_X1.shape[0],1)
practice_axis_Y1 = interim

In [30]:
phi1 = straight_perp(practice_axis_X1,practice_axis_Y1,weight1)

In [31]:
phi1

array([[ 148.17571126],
       [-100.70689062],
       [ -79.94258139],
       [ -68.96192897],
       [   5.13120649]])

In [32]:
validity1 = 0  #testing data for datafile2
trial_axis_X1 = info_wiping(info_trial1)
trial_axis_Y1 = info_trial1[info_trial1.columns[-1]] 

In [33]:
predict_axis_Y1 = mynumpy.dot(trial_axis_X1,phi1)

In [34]:
invalid = 0
i=0
while(i<len(trial_axis_Y1)):
    if predict_axis_Y1[i]<0 and trial_axis_Y1.iloc[i]>0:
        invalid+=1
    elif predict_axis_Y1[i]>0 and trial_axis_Y1.iloc[i]<0:
        invalid+=1
    i=i+1

In [35]:
validity1 = (1 - (invalid/len(trial_axis_Y1)))*100

In [36]:
validity1

98.30097087378641